version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx1024m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Chmod gradlew
          command: chmod +x gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew --no-daemon androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run tests on Debug
          command: ./gradlew --no-daemon clean assembleDebug testDebugUnitTest
      - run:
          name: Run tests on Release
          command: ./gradlew --no-daemon clean assembleRelease testReleaseUnitTest lintRelease
      - run:
          name: Run Coverage
          command: |
                   ./gradlew --no-daemon jacocoTestReport
                   bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results